### ISSUE TITLE
User still gets activation mail, even if registration notification is on.

### ISSUE THREAD

**Issue by noregt** [olivierbon/craft-concierge#4]
Hi,

When a user registers, the admin gets the registration notification, but the user also receives the activation link email.

This is Craft 3.1.13

**Comment by olivierbon** [comment]
You need to uncheck 'Verify email addresses' in /admin/settings/users/settings

**Comment by kellyannmcnamara01** [comment]
Hello,

In Craft CMS 3.1.28 I have unchecked 'Verify email addresses' in /admin/settings/users/settings and the users are still being set as disabled, not pending. 

I found this response from [this](https://github.com/olivierbon/craft-concierge/issues/5) issue.

**Comment by olivierbon** [comment]
Hey,

This is expected behaviour so that Concierge integrates with Craft's email verification workflow (if/when enabled).

Concierge **Suspends** users and Craft sets them to **Pending** if you enable email verification. So...

**With** email validation the flow is:

- User registers
- Craft sets the user as **Pending** AND Concierge as **Suspended**

Next,

- User clicks the verification link, verify email BUT still can't access the site (Suspended)
- Admin unsuspends - User can get in (Active)
OR
- Admin unsuspends - User can't get in as still pending email verification (Pending)
- User click verification link, verify email and can now access the site (Active)

**Without** email validation the flow is:

- User registers
- Concierge **Suspends**
- Admin unsuspends - User can get in (Active)

In Craft, a **Pending** user is a user that needs to validate her/his email. A **Suspended** user IS validated, it just cannot log in.

The pending status is linked tightly to the email verification and as you can't yet have custom statuses, the **Suspended** status was the only option which ended up making sense in the end as Concierge needed 2 'locked states' for each user. 

I hope that clarifies things :)
